### ISSUE TITLE
下载好的Demo运行就崩溃

### ISSUE THREAD

**Issue by caopeng000** [liuling07/MultiTaskAndThreadDownload#1]
Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.bbk.lling.multitaskdownload.beans.AppContent$Status)
                                                                                     at android.os.Parcel.readSerializable(Parcel.java:2512)
                                                                                     at android.os.Parcel.readValue(Parcel.java:2315)
                                                                                     at com.bbk.lling.multitaskdownload.beans.AppContent$1.createFromParcel(AppContent.java:93)
                                                                                     at com.bbk.lling.multitaskdownload.beans.AppContent$1.createFromParcel(AppContent.java:85)
                                                                                     at android.os.Parcel.readParcelable(Parcel.java:2367)
                                                                                     at android.os.Parcel.readValue(Parcel.java:2264)
                                                                                     at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                                                                     at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                                                                     at android.os.Bundle.getParcelable(Bundle.java:786)
                                                                                     at android.content.Intent.getParcelableExtra(Intent.java:5381)
                                                                                     at com.bbk.lling.multitaskdownload.activitys.MainActivity$2.onReceive(MainActivity.java:93)
                                                                                     at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:883)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5432) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)

**Comment by yhb612** [comment]
确实是这样
